In [3]:
import torch
print(torch.__version__)

1.8.1


In [5]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
torch.numel(tensor_arr)

6

In [4]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [7]:
torch.is_tensor(tensor_arr)

True

In [10]:
tensor_initialized = torch.rand(2,5)
tensor_initialized

tensor([[0.1817, 0.4027, 0.5067, 0.6227, 0.8792],
        [0.9898, 0.0859, 0.2184, 0.5435, 0.1782]])

In [11]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

<ipython-input-11-13d21c85b74a>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])


tensor([1, 2, 3], dtype=torch.int16)

In [13]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [14]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [15]:
tensor_ones = torch.ones((2,4), dtype=torch.int32)
tensor_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [16]:
tensor_zeros = torch.zeros_like(tensor_ones)
tensor_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [17]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [23]:
i = torch.tensor([[0, 1, 1],
                  [2, 2, 0]])
v = torch.tensor([3,4,5])

In [24]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3, 4, 5]),
       size=(2, 5), nnz=3, layout=torch.sparse_coo)

Operations that modify the tensor in-place have an "_" suffix

In [25]:
init_tensor = torch.rand(2,3)
init_tensor

tensor([[0.0886, 0.0393, 0.7151],
        [0.9506, 0.6663, 0.7093]])

In [28]:
init_tensor.fill_(10)
init_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [29]:
new_based_on_init = init_tensor.add(101)
new_based_on_init

tensor([[111., 111., 111.],
        [111., 111., 111.]])

In [30]:
init_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [31]:
init_tensor.add_(8)
init_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [32]:
new_based_on_init.sqrt_()
new_based_on_init

tensor([[10.5357, 10.5357, 10.5357],
        [10.5357, 10.5357, 10.5357]])

In [34]:
x = torch.linspace(start=0.0, end=10.0, steps=15)
x

tensor([ 0.0000,  0.7143,  1.4286,  2.1429,  2.8571,  3.5714,  4.2857,  5.0000,
         5.7143,  6.4286,  7.1429,  7.8571,  8.5714,  9.2857, 10.0000])

In [35]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.0000, 0.7143, 1.4286, 2.1429, 2.8571]),
 tensor([3.5714, 4.2857, 5.0000, 5.7143, 6.4286]),
 tensor([ 7.1429,  7.8571,  8.5714,  9.2857, 10.0000]))

In [41]:
tens_1 = tensor_chunk[0]
tens_2 = tensor_chunk[1]
tens_3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tens_1, tens_2, tens_3),0)

tensor([0.0000, 0.7143, 1.4286, 2.1429, 2.8571, 3.5714, 4.2857, 5.0000, 5.7143,
        6.4286, 3.0000, 4.0000, 5.0000])

In [43]:
random_tensor = torch.Tensor([[10, 8, 30], [40,5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [44]:
random_tensor[0,1]

tensor(8.)

In [45]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [46]:
random_tensor.size()

torch.Size([3, 3])

In [48]:
random_tensor[2,2]=100
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [50]:
random_tensor.shape

torch.Size([3, 3])

In [53]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [54]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [55]:
init_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [58]:
tensor_transpose = torch.transpose(init_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [60]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [59]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [61]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [62]:
tensor_clamp = torch.clamp(random_tensor, min = 10, max=40)
tensor_clamp

tensor([[10., 10., 30.],
        [40., 10., 10.],
        [12., 10., 40.]])

In [65]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [64]:
torch.argmax(random_tensor, dim=1)

tensor([2, 0, 2])

In [66]:
torch.argmin(random_tensor, dim=1)

tensor([1, 1, 1])