In [1]:
import torch

In [3]:
x = torch.rand(3, requires_grad=True)
x

tensor([0.7726, 0.8909, 0.5929], requires_grad=True)

In [4]:
y = x+2
y

tensor([2.7726, 2.8909, 2.5929], grad_fn=<AddBackward0>)

In [5]:
z = y*y*2
z

tensor([15.3751, 16.7145, 13.4464], grad_fn=<MulBackward0>)

In [6]:
z = z.mean()
z

tensor(15.1787, grad_fn=<MeanBackward0>)

In [7]:
z.backward() #dz/dx
x.grad

tensor([3.6969, 3.8545, 3.4572])