In [1]:
import torch

In [5]:
x = torch.empty(3)
x

tensor([0.0000e+00, 8.5899e+09, 0.0000e+00])

In [6]:
x = torch.rand(2,2)
x

tensor([[0.0863, 0.5275],
        [0.7418, 0.4141]])

In [7]:
x = torch.zeros(3)
x

tensor([0., 0., 0.])

In [9]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [12]:
d = torch.ones(2,2, dtype=torch.double)
d

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [13]:
f16 = torch.ones(2,2, dtype=torch.float16)
f16

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [16]:
f16.size()

torch.Size([2, 2])

In [17]:
x = torch.rand(2,2)
x

tensor([[0.7941, 0.5833],
        [0.8783, 1.0324]])

In [18]:
y = torch.rand(2,2)
y

tensor([[0.5042, 0.4450],
        [0.3861, 0.8472]])

In [19]:
z=x+y
z

tensor([[1.1705, 0.5302],
        [0.4912, 1.6008]])

In [20]:
z2 = torch.add(x,y)
z2

tensor([[1.1705, 0.5302],
        [0.4912, 1.6008]])

In [22]:
x = torch.rand(5, 3)
x

tensor([[0.1518, 0.7776, 0.7333],
        [0.0045, 0.6724, 0.1560],
        [0.1171, 0.4250, 0.9804],
        [0.7928, 0.2273, 0.3300],
        [0.8522, 0.2719, 0.9283]])

In [23]:
x[1,:]

tensor([0.0045, 0.6724, 0.1560])

In [24]:
x[2,2]

tensor(0.9804)

In [25]:
x[2,2].item()

0.9804087281227112

In [30]:
x = torch.rand(4,4)
x.size()

torch.Size([4, 4])

In [31]:
y = x.view(16)
y.size()

torch.Size([16])

In [32]:
y = x.view(-1,8)
y.size()

torch.Size([2, 8])

In [33]:
import numpy as np

In [34]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [37]:
b = a.numpy()
type(b)

numpy.ndarray

In [38]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [39]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [40]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [41]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)